x-shared-postgres-env: &postgres-env
  POSTGRES_USER: root
  POSTGRES_PASSWORD: 1234

x-shared-minio-env: &minio-env
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: 12345678

x-shared-env: &shared-env
  ASPNETCORE_ENVIRONMENT: Staging
  ProvaPraticaDbContextConnectionStrings: Host=host.docker.internal;Port=5432;Database=provapratica;
  AmazonS3BaseUrl: http://host.docker.internal:9000
  <<: 
    - *postgres-env
    - *minio-env

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      <<: *postgres-env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      <<: *minio-env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    
  provapratica:
    build: .
    container_name: provapratica
    restart: always
    environment:
      <<: *shared-env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio

volumes:
  postgres_data:
  minio_data: